# MRL KISSMatcher Configuration

mrl_slave:
  ros__parameters:
    kissmatcher:
      use_voxel_sampling: true
      voxel_size: 0.3
      normal_radius: 0.9
      fpfh_radius: 1.5
      thr_linearity: 1.0

mrl_master:
  ros__parameters:
    kissmatcher:
      voxel_size: 0.3
      robin_noise_bound_gain: 1.0
      solver_noise_bound_gain: 0.75
